/control/verbose 2
/run/verbose 2

/HPGe_simulation/det/setDetectorMoveX 1219
/HPGe_simulation/det/setDetectorMoveY 210
/HPGe_simulation/det/setDetectorMoveZ 665.5

/run/numberOfThreads 8
/run/initialize
/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh true
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 2 45. 45.
/vis/viewer/zoom 2.35
/vis/viewer/set/style wireframe
/vis/scene/add/axes 0 0 0 1000 mm
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
#/tracking/storeTrajectory 10
/vis/scene/endOfEventAction accumulate
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/vis/ogl/set/displayListLimit 1000000

#/run/beamOn 10


